packages:
  - 'packages/*'
  - 'plugins/*'
  - 'docs'
allowBuilds:
  esbuild: true

catalog:
  typescript: '^6.0.0'
  vitest: '^4.0.0'
  tsdown: '^0.22.3'
  jiti: '^2.7.0'
  tsx: '^4.22.4'
  '@logtape/logtape': '^2.0.0'
  cleye: '^2.0.0'
  zod: '^4.4.3'
  '@types/node': '^22.20.0'
  '@clack/prompts': '^1.0.0'
