/**
 * output-generators.ts — OpenCode output file generators
 *
 * These functions generate the two output files for the OpenCode adapter:
 * 1. `{pluginName}.ts` - The TypeScript plugin file with hook handlers
 * 2. `opencode.json` - The plugin manifest configuration
 */

import type { FileOutput, PluginManifest } from "@agentplugin/core";

// ─── Plugin File Generator ────────────────────────────────────────────────────

/**
 * Generates the TypeScript plugin file content.
 *
 * @param manifest - The plugin manifest
 * @param hookCodeMap - Map of OpenCode hook names to their handler code strings
 * @returns FileOutput with path `{pluginName}.ts` and TypeScript content
 */
export function generatePluginFile(
  manifest: PluginManifest,
  hookCodeMap: Map<string, string>
): FileOutput {
  const pluginFileName = `${manifest.name}.ts`;

  // Build hook entries from the hookCodeMap
  const hookEntries: string[] = [];
  for (const [hookName, handlerCode] of hookCodeMap) {
    hookEntries.push(
      `    "${hookName}": async (${getHookParams(hookName)}) => {\n${indentHandler(handlerCode)}\n    }`
    );
  }

  const pluginFileContent = [
    `// Auto-generated by AgentBridge for OpenCode`,
    `// Plugin: ${manifest.name}`,
    `// Description: ${manifest.description ?? "No description provided"}`,
    ``,
    `/**`,
    ` * ${manifest.name} — OpenCode Plugin`,
    ` *`,
    ` * This module was generated by @agentplugin/adapter-opencode.`,
    ` * Drop this file into \`.opencode/plugins/\` or`,
    ` * \`~/.config/opencode/plugins/\` to activate.`,
    ` */`,
    ``,
    `export default async function(ctx) {`,
    `  return {`,
    hookEntries.join(",\n"),
    `  };`,
    `}`,
    ``,
  ].join("\n");

  return {
    path: pluginFileName,
    content: pluginFileContent,
  };
}

/**
 * Gets the appropriate parameter string for a given OpenCode hook name.
 */
function getHookParams(hookName: string): string {
  switch (hookName) {
    case "event":
      return "{ event }";
    case "tool.execute.before":
      return "input, output";
    case "tool.execute.after":
      return "input, output";
    case "permission.ask":
      return "{ permission }";
    case "experimental.session.compacting":
      return "{ event }";
    default:
      return "{}";
  }
}

/**
 * Indents the handler code by 4 spaces for proper TypeScript nesting.
 */
function indentHandler(handlerCode: string): string {
  return handlerCode
    .split("\n")
    .map((line) => `        ${line}`)
    .join("\n");
}

// ─── Manifest Generator ──────────────────────────────────────────────────────

/**
 * Generates the opencode.json manifest file content.
 *
 * @param manifest - The plugin manifest
 * @param hooks - Map of OpenCode hook names to their handler code strings
 * @returns FileOutput with path `opencode.json` and JSON content
 */
export function generateManifest(
  manifest: PluginManifest,
  hooks: Map<string, string>
): FileOutput {
  const configFileName = "opencode.json";

  const opencodeConfig = {
    name: manifest.name,
    description: manifest.description ?? "",
    version: manifest.version ?? "0.1.0",
    author: manifest.author ?? "",
    license: manifest.license ?? "MIT",
    hooks: Object.fromEntries(
      Array.from(hooks.keys()).map((k) => [k, true])
    ),
    tools:
      manifest.tools?.map((tool) => ({
        name: tool.name,
        description: tool.description,
        parameters: tool.parameters,
      })) ?? [],
    discovery: {
      paths: [".opencode/plugins/", "~/.config/opencode/plugins/"],
    },
  };

  const configFileContent = JSON.stringify(opencodeConfig, null, 2);

  return {
    path: configFileName,
    content: configFileContent,
  };
}
