/**
 * output-generators.ts — OpenCode output file generators
 *
 * These functions generate output files for the OpenCode adapter:
 * 1. `plugins/{pluginName}.ts` - The TypeScript plugin file with hook handlers
 * 2. `opencode.json` - The plugin manifest configuration
 * 3. `command/{name}.md` - One file per command (optional)
 * 4. `agent/{name}.md` - One file per agent definition (optional)
 */

import type { PluginManifest } from "@agentplugins/core";
import type { FileOutput } from "@agentplugins/core/adapter";
import { sanitizeJoin } from "@agentplugins/compile";

/** Last path segment — ponytail: avoids a node:path dev-dependency in generated dts. */
function basename(p: string): string {
  return p.replace(/\\/g, "/").split("/").pop() || p;
}

/** Resolve a manifest path safely; clamps traversal attempts to the plugin root. */
function safeResolve(base: string, untrusted: string): string {
  try {
    return sanitizeJoin(base, untrusted);
  } catch {
    return sanitizeJoin(base, basename(untrusted));
  }
}

// ─── Plugin File Generator ────────────────────────────────────────────────────

/**
 * Generates the TypeScript plugin file content.
 *
 * @param manifest - The plugin manifest
 * @param hookCodeMap - Map of OpenCode hook names to their handler code strings
 * @param pluginRoot - Optional plugin root for safe path resolution
 * @returns FileOutput with path `{pluginName}.ts` and TypeScript content
 */
export function generatePluginFile(
  manifest: PluginManifest,
  hookCodeMap: Map<string, string>,
  pluginRoot?: string
): FileOutput {
  // Plugin lives under plugins/ subdir so OpenCode discovers it at plugins/<name>.ts
  const pluginFileName = `plugins/${manifest.name}.ts`;

  // Build hook entries from the hookCodeMap
  const hookEntries: string[] = [];
  for (const [hookName, handlerCode] of hookCodeMap) {
    hookEntries.push(
      `    "${hookName}": async (${getHookParams(hookName)}) => {\n${indentHandler(handlerCode)}\n    }`
    );
  }

  // Emit __pluginRoot when any hook uses a command-type handler (needs file resolution)
  const hasCommandHandler = Object.values(manifest.hooks ?? {}).some(
    (h) => h?.handler?.type === "command"
  );
  // plugins/<name>.ts is 3 dirs deep inside the store: .agentplugins-dist/opencode/plugins/
  const pluginRootLine = hasCommandHandler
    ? `  const __pluginRoot = new URL('../../../', import.meta.url).pathname.replace(/\\/$/, '');\n`
    : "";

  const overridePath = manifest.adapterOverrides?.opencode;
  const safeOverride = overridePath && pluginRoot ? safeResolve(pluginRoot, overridePath) : overridePath;
  const overrideBlock = safeOverride
    ? [
        `  // Runtime adapter override — tries user file first, falls back to codegen.`,
        ...(pluginRoot
          ? [
              `  console.warn('[agentplugins] Loading adapter override from ' + ${JSON.stringify(safeOverride)} + ' — only install overrides from plugins you trust');`,
            ]
          : []),
        `  try {`,
        `    const overrideMod = await import(${JSON.stringify(safeOverride)});`,
        `    if (typeof overrideMod.default === 'function') {`,
        `      return overrideMod.default(ctx);`,
        `    }`,
        `  } catch {`,
        `    // Override not found — using generated implementation`,
        `  }`,
        ``,
      ].join("\n")
    : "";

  const pluginFileContent = [
    `// Auto-generated by AgentPlugins for OpenCode`,
    `// Plugin: ${manifest.name}`,
    `// Description: ${manifest.description ?? "No description provided"}`,
    ``,
    `/**`,
    ` * ${manifest.name} — OpenCode Plugin`,
    ` *`,
    ` * This module was generated by @agentplugins/adapter-opencode.`,
    ` * Drop this file into \`.opencode/plugins/\` or`,
    ` * \`~/.config/opencode/plugins/\` to activate.`,
    ` */`,
    ``,
    `export default async function(ctx) {`,
    pluginRootLine,
    overrideBlock,
    `  return {`,
    hookEntries.join(",\n"),
    `  };`,
    `}`,
    ``,
  ].join("\n");

  return {
    path: pluginFileName,
    content: pluginFileContent,
  };
}

/**
 * Gets the appropriate parameter string for a given OpenCode hook name.
 */
function getHookParams(hookName: string): string {
  switch (hookName) {
    case "event":
      return "{ event }";
    case "tool.execute.before":
      return "input, output";
    case "tool.execute.after":
      return "input, output";
    case "permission.ask":
      return "{ permission }";
    case "experimental.session.compacting":
      return "{ event }";
    default:
      return "{}";
  }
}

/**
 * Indents the handler code by 4 spaces for proper TypeScript nesting.
 */
function indentHandler(handlerCode: string): string {
  return handlerCode
    .split("\n")
    .map((line) => `        ${line}`)
    .join("\n");
}

// ─── Manifest Generator ──────────────────────────────────────────────────────

/**
 * Generates the opencode.json manifest file content.
 *
 * @param manifest - The plugin manifest
 * @param hooks - Map of OpenCode hook names to their handler code strings
 * @returns FileOutput with path `opencode.json` and JSON content
 */
export function generateManifest(
  manifest: PluginManifest,
  hooks: Map<string, string>
): FileOutput {
  const configFileName = "opencode.json";

  const opencodeConfig = {
    name: manifest.name,
    description: manifest.description ?? "",
    version: manifest.version ?? "0.1.0",
    author: manifest.author ?? "",
    license: manifest.license ?? "MIT",
    hooks: Object.fromEntries(
      Array.from(hooks.keys()).map((k) => [k, true])
    ),
    tools:
      manifest.tools?.map((tool) => ({
        name: tool.name,
        description: tool.description,
        parameters: tool.parameters,
      })) ?? [],
    discovery: {
      paths: [".opencode/plugins/", "~/.config/opencode/plugins/"],
    },
  };

  const configFileContent = JSON.stringify(opencodeConfig, null, 2);

  return {
    path: configFileName,
    content: configFileContent,
  };
}

// ─── Command File Generator ───────────────────────────────────────────────────

/**
 * Generates one `command/<name>.md` file per command in the manifest.
 * Format follows OpenCode's native command layout: YAML frontmatter + prompt body.
 * Universal `{{args}}` placeholders are replaced with OpenCode's `$ARGUMENTS`.
 */
export function generateCommandFiles(manifest: PluginManifest): FileOutput[] {
  return (manifest.commands ?? []).map((cmd) => {
    const prompt = (cmd.prompt ?? "").replace(/\{\{args\}\}/g, "$ARGUMENTS");
    const descLine = cmd.description ? `description: ${cmd.description}` : `description: ""`;
    const content = [`---`, descLine, `---`, ``, prompt, ``].join("\n");
    return { path: `command/${cmd.name}.md`, content };
  });
}

// ─── Agent File Generator ─────────────────────────────────────────────────────

/**
 * Generates one `agent/<name>.md` file per agent definition in the manifest.
 */
export function generateAgentFiles(manifest: PluginManifest): FileOutput[] {
  return (manifest.agents ?? []).map((agent) => {
    const lines = ["---", `description: ${agent.description ?? ""}`];
    if (agent.tools && agent.tools.length > 0) {
      lines.push(`tools: [${agent.tools.join(", ")}]`);
    }
    lines.push("---", "", agent.prompt ?? "", "");
    const content = lines.join("\n");
    return { path: `agent/${agent.name}.md`, content };
  });
}
