import type {
  PluginManifest,
  UniversalHookName,
  FileOutput,
  HookDefinition,
} from '@agentplugins/contract';

export type EmitLanguage = 'typescript' | 'javascript' | 'go';

export interface CompiledHook {
  name: UniversalHookName;
  matcher?: string;
  handlerType: 'command' | 'http' | 'inline' | 'reference';
  command?: string;
  url?: string;
  headers?: Record<string, string>;
  reference?: string;
  inlineSource?: string;
}

export interface CodeEmitter {
  readonly language: EmitLanguage;
  emit(manifest: PluginManifest, hooks: CompiledHook[]): FileOutput[];
}

export function extractCompiledHooks(manifest: PluginManifest): CompiledHook[] {
  const hooks = manifest.hooks;
  if (!hooks) return [];

  const compiled: CompiledHook[] = [];
  for (const name of Object.keys(hooks) as UniversalHookName[]) {
    const def: HookDefinition | undefined = hooks[name];
    if (!def) continue;

    const handler = def.handler;
    const entry: CompiledHook = {
      name,
      handlerType: handler.type,
      ...(def.matcher !== undefined ? { matcher: def.matcher } : {}),
    };

    if (handler.type === 'command') {
      entry.command = handler.command;
    } else if (handler.type === 'http') {
      entry.url = handler.url;
      if (handler.headers) entry.headers = { ...handler.headers };
    } else {
      entry.inlineSource = `// inline handler for ${name} — emit at build time`;
    }

    compiled.push(entry);
  }

  return compiled;
}

function escapeStr(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

function pascalCase(name: string): string {
  if (name.length === 0) return name;
  const first = name.charAt(0).toUpperCase();
  const rest = name.slice(1);
  const parts = rest.split(/(?=[A-Z])/).map((p) => p.charAt(0).toUpperCase() + p.slice(1));
  return first + parts.join('');
}

function hookEntry(hook: CompiledHook): string {
  switch (hook.handlerType) {
    case 'command':
      return `{ command: "${escapeStr(hook.command ?? '')}" }`;
    case 'http':
      return `{ http: "${escapeStr(hook.url ?? '')}" }`;
    case 'inline':
      return `{ handler: ${hook.inlineSource ?? 'null'} }`;
    case 'reference':
      return `{ ref: "${escapeStr(hook.reference ?? '')}" }`;
    default:
      return `{}`;
  }
}

function buildHooksMap(hooks: CompiledHook[]): string {
  const indent = '  ';
  const lines = hooks.map((h) => `${indent}${h.name}: ${hookEntry(h)},`);
  return `{\n${lines.join('\n')}\n}`;
}

function buildSummary(manifest: PluginManifest, hooks: CompiledHook[]): string {
  return JSON.stringify(
    {
      name: manifest.name,
      version: manifest.version,
      hooks: hooks.map((h) => h.name),
    },
    null,
    2
  );
}

function buildHeaderComment(manifest: PluginManifest): string {
  return [
    `/**`,
    ` * Generated by AgentPlugins`,
    ` * Plugin: ${manifest.name} v${manifest.version}`,
    ` * DO NOT EDIT — regenerated on build.`,
    ` */`,
  ].join('\n');
}

export const TypeScriptEmitter: CodeEmitter = {
  language: 'typescript',
  emit(manifest: PluginManifest, hooks: CompiledHook[]): FileOutput[] {
    const header = buildHeaderComment(manifest);
    const hooksMap = buildHooksMap(hooks);
    const summary = buildSummary(manifest, hooks);
    const content = `${header}

export const hooks = ${hooksMap};

const plugin = ${summary};

export default plugin;
`;

    return [{ path: 'index.ts', content }];
  },
};

function buildHooksDTS(hooks: CompiledHook[]): string {
  const indent = '  ';
  const lines = hooks.map((h) => `${indent}${h.name}: Record<string, unknown>;`);
  return `{\n${lines.join('\n')}\n}`;
}

export const JavaScriptEmitter: CodeEmitter = {
  language: 'javascript',
  emit(manifest: PluginManifest, hooks: CompiledHook[]): FileOutput[] {
    const header = buildHeaderComment(manifest);
    const hooksMap = buildHooksMap(hooks);
    const summary = buildSummary(manifest, hooks);

    const jsContent = `${header}

export const hooks = ${hooksMap};

const plugin = ${summary};

export default plugin;
`;

    const hooksDTS = buildHooksDTS(hooks);
    const dtsContent = `${header}

export const hooks: ${hooksDTS};

export interface PluginSummary {
  name: string;
  version: string;
  hooks: string[];
}

declare const plugin: PluginSummary;
export default plugin;
`;

    return [
      { path: 'index.js', content: jsContent },
      { path: 'index.d.ts', content: dtsContent },
    ];
  },
};

export const GoEmitter: CodeEmitter = {
  language: 'go',
  emit(manifest: PluginManifest, hooks: CompiledHook[]): FileOutput[] {
    const header = '// Code generated by AgentPlugins. DO NOT EDIT.';
    const pkgLine = `package main`;
    const imports = hooks.length > 0 ? `\nimport "context"\n` : '';

    const funcs = hooks.map((h) => {
      const fnName = `On${pascalCase(h.name)}`;
      return [
        `func ${fnName}(ctx context.Context) error {`,
        `\t// TODO: implement ${h.handlerType} handler`,
        `\treturn nil`,
        `}`,
      ].join('\n');
    });

    const registrations = hooks.map((h) => `\t// register On${pascalCase(h.name)}`).join('\n');

    const initFn = hooks.length > 0
      ? `\nfunc init() {\n${registrations}\n}\n`
      : '\nfunc init() {}\n';

    const pluginComment = `// Plugin: ${manifest.name} v${manifest.version}`;

    const content = [
      header,
      pkgLine,
      pluginComment,
      imports,
      ...funcs,
      initFn,
    ]
      .filter((part) => part.length > 0)
      .join('\n');

    return [{ path: 'main.go', content }];
  },
};

const EMITTERS: Record<EmitLanguage, CodeEmitter> = {
  typescript: TypeScriptEmitter,
  javascript: JavaScriptEmitter,
  go: GoEmitter,
};

export function getEmitter(language: EmitLanguage): CodeEmitter {
  const emitter = EMITTERS[language];
  if (!emitter) {
    throw new Error(`Unknown emit language: ${String(language)}`);
  }
  return emitter;
}
