/**
 * output-generators.test.ts — TDD RED phase tests
 *
 * These tests define the expected behavior of the output generator functions
 * for the OpenCode adapter: generatePluginFile() and generateManifest().
 */

import { describe, it, expect } from "vitest";
import type { PluginManifest, HookDefinition, FileOutput } from "@agentplugins/core";
import {
  generatePluginFile,
  generateManifest,
  generateCommandFiles,
  generateAgentFiles,
} from "../src/output-generators";

// ─── Test Fixtures ───────────────────────────────────────────────────────────

const minimalManifest: PluginManifest = {
  name: "test-plugin",
  version: "1.0.0",
  description: "A minimal test plugin",
};

const fullManifest: PluginManifest = {
  name: "my-opencode-plugin",
  version: "2.1.0",
  description: "A full-featured OpenCode plugin",
  author: "Test Author",
  license: "MIT",
  tools: [
    {
      name: "greet",
      description: "Greets the user",
      parameters: {
        type: "object",
        properties: {
          name: { type: "string", description: "Name to greet" },
        },
        required: ["name"],
      },
    },
  ],
  hooks: {
    sessionStart: {
      handler: {
        type: "inline",
        handler: async () => ({}),
      },
    },
    preToolUse: {
      handler: {
        type: "inline",
        handler: async () => ({}),
      },
    },
  },
};

const singleHookCodeMap = new Map<string, string>([
  ["tool.execute.before", `async ({ toolName, toolInput }) => {\n      // handler\n    }`],
]);

const multiHookCodeMap = new Map<string, string>([
  [
    "event",
    `async ({ event }) => {\n      if (event.type === "session.created") {\n        // sessionStart handler\n      }\n      if (event.type === "session.deleted") {\n        // sessionEnd handler\n      }\n    }`,
  ],
  ["tool.execute.before", `async ({ toolName, toolInput }) => {\n      // preToolUse handler\n    }`],
  ["tool.execute.after", `async ({ toolName, output }) => {\n      // postToolUse handler\n    }`],
]);

// ─── generatePluginFile() Tests ──────────────────────────────────────────────

describe("generatePluginFile()", () => {
  describe("file output structure", () => {
    it("returns FileOutput with path 'plugins/{pluginName}.ts'", () => {
      const result = generatePluginFile(minimalManifest, singleHookCodeMap);
      expect(result.path).toBe("plugins/test-plugin.ts");
    });

    it("returns object with 'path' and 'content' properties", () => {
      const result = generatePluginFile(minimalManifest, singleHookCodeMap);
      expect(result).toHaveProperty("path");
      expect(result).toHaveProperty("content");
      expect(typeof result.path).toBe("string");
      expect(typeof result.content).toBe("string");
    });
  });

  describe("TypeScript content", () => {
    it("contains 'export default async function(ctx)' signature", () => {
      const result = generatePluginFile(minimalManifest, singleHookCodeMap);
      expect(result.content).toContain("export default async function(ctx)");
    });

    it("contains proper header comments", () => {
      const result = generatePluginFile(fullManifest, singleHookCodeMap);
      expect(result.content).toContain("// Auto-generated by AgentPlugins for OpenCode");
      expect(result.content).toContain(`// Plugin: ${fullManifest.name}`);
      expect(result.content).toContain(`// Description: ${fullManifest.description}`);
    });

    it("contains OpenCode plugin documentation comment block", () => {
      const result = generatePluginFile(fullManifest, singleHookCodeMap);
      expect(result.content).toContain("/**");
      expect(result.content).toContain(`${fullManifest.name} — OpenCode Plugin`);
      expect(result.content).toContain("This module was generated by @agentplugins/adapter-opencode");
      expect(result.content).toContain("*/");
    });

    it("returns object with hook keys from hookCodeMap", () => {
      const result = generatePluginFile(minimalManifest, singleHookCodeMap);
      expect(result.content).toContain('"tool.execute.before"');
    });

    it("contains handler invocation string from hookCodeMap", () => {
      const result = generatePluginFile(minimalManifest, singleHookCodeMap);
      expect(result.content).toContain("async ({ toolName, toolInput })");
    });
  });

  describe("with single hook", () => {
    it("generates valid TypeScript with one hook", () => {
      const result = generatePluginFile(minimalManifest, singleHookCodeMap);
      // Should have return statement with the hook
      expect(result.content).toContain("return {");
      expect(result.content).toContain("};");
    });
  });

  describe("with multiple hooks", () => {
    it("generates valid TypeScript with multiple hooks", () => {
      const result = generatePluginFile(fullManifest, multiHookCodeMap);
      expect(result.content).toContain("return {");
      expect(result.content).toContain("};");
      // All hooks from hookCodeMap should be present
      expect(result.content).toContain('"event"');
      expect(result.content).toContain('"tool.execute.before"');
      expect(result.content).toContain('"tool.execute.after"');
    });
  });

  describe("with minimal manifest", () => {
    it("works with just name and version", () => {
      const manifest: PluginManifest = {
        name: "minimal",
        version: "0.0.1",
        description: "",
      };
      const result = generatePluginFile(manifest, new Map());
      expect(result.path).toBe("plugins/minimal.ts");
      expect(result.content).toContain("export default async function(ctx)");
    });
  });
});

// ─── generateManifest() Tests ────────────────────────────────────────────────

describe("generateManifest()", () => {
  describe("file output structure", () => {
    it("returns FileOutput with path 'opencode.json'", () => {
      const result = generateManifest(minimalManifest, new Map());
      expect(result.path).toBe("opencode.json");
    });

    it("returns object with 'path' and 'content' properties", () => {
      const result = generateManifest(minimalManifest, new Map());
      expect(result).toHaveProperty("path");
      expect(result).toHaveProperty("content");
      expect(typeof result.path).toBe("string");
      expect(typeof result.content).toBe("string");
    });
  });

  describe("JSON structure", () => {
    it("contains valid JSON", () => {
      const result = generateManifest(minimalManifest, new Map());
      expect(() => JSON.parse(result.content)).not.toThrow();
    });

    it("contains name from manifest", () => {
      const result = generateManifest(fullManifest, new Map());
      const parsed = JSON.parse(result.content);
      expect(parsed.name).toBe(fullManifest.name);
    });

    it("contains version from manifest", () => {
      const result = generateManifest(fullManifest, new Map());
      const parsed = JSON.parse(result.content);
      expect(parsed.version).toBe(fullManifest.version);
    });

    it("contains description from manifest", () => {
      const result = generateManifest(fullManifest, new Map());
      const parsed = JSON.parse(result.content);
      expect(parsed.description).toBe(fullManifest.description);
    });

    it("contains author from manifest when present", () => {
      const result = generateManifest(fullManifest, new Map());
      const parsed = JSON.parse(result.content);
      expect(parsed.author).toBe(fullManifest.author);
    });

    it("contains license from manifest when present", () => {
      const result = generateManifest(fullManifest, new Map());
      const parsed = JSON.parse(result.content);
      expect(parsed.license).toBe(fullManifest.license);
    });

    it("defaults author to empty string when not provided", () => {
      const result = generateManifest(minimalManifest, new Map());
      const parsed = JSON.parse(result.content);
      expect(parsed.author).toBe("");
    });

    it("defaults license to 'MIT' when not provided", () => {
      const result = generateManifest(minimalManifest, new Map());
      const parsed = JSON.parse(result.content);
      expect(parsed.license).toBe("MIT");
    });
  });

  describe("hooks object", () => {
    it("contains hooks object mapping OpenCode hook names to true", () => {
      const result = generateManifest(fullManifest, multiHookCodeMap);
      const parsed = JSON.parse(result.content);
      expect(parsed.hooks).toBeDefined();
      expect(parsed.hooks).toBeInstanceOf(Object);
    });

    it("maps each hook key to true", () => {
      const result = generateManifest(fullManifest, multiHookCodeMap);
      const parsed = JSON.parse(result.content);
      expect(parsed.hooks["event"]).toBe(true);
      expect(parsed.hooks["tool.execute.before"]).toBe(true);
      expect(parsed.hooks["tool.execute.after"]).toBe(true);
    });

    it("contains only hooks that are in the hookCodeMap", () => {
      const result = generateManifest(fullManifest, singleHookCodeMap);
      const parsed = JSON.parse(result.content);
      const hookKeys = Object.keys(parsed.hooks);
      expect(hookKeys).toHaveLength(1);
      expect(hookKeys).toContain("tool.execute.before");
    });
  });

  describe("discovery paths", () => {
    it("contains discovery paths array", () => {
      const result = generateManifest(fullManifest, new Map());
      const parsed = JSON.parse(result.content);
      expect(parsed.discovery).toBeDefined();
      expect(parsed.discovery.paths).toBeInstanceOf(Array);
    });

    it("contains standard OpenCode plugin paths", () => {
      const result = generateManifest(fullManifest, new Map());
      const parsed = JSON.parse(result.content);
      expect(parsed.discovery.paths).toContain(".opencode/plugins/");
      expect(parsed.discovery.paths).toContain("~/.config/opencode/plugins/");
    });
  });

  describe("tools array", () => {
    it("contains tools array when manifest has tools", () => {
      const result = generateManifest(fullManifest, new Map());
      const parsed = JSON.parse(result.content);
      expect(parsed.tools).toBeInstanceOf(Array);
      expect(parsed.tools).toHaveLength(1);
    });

    it("contains tool with name, description, and parameters", () => {
      const result = generateManifest(fullManifest, new Map());
      const parsed = JSON.parse(result.content);
      expect(parsed.tools[0].name).toBe("greet");
      expect(parsed.tools[0].description).toBe("Greets the user");
      expect(parsed.tools[0].parameters).toBeDefined();
    });

    it("contains empty tools array when manifest has no tools", () => {
      const result = generateManifest(minimalManifest, new Map());
      const parsed = JSON.parse(result.content);
      expect(parsed.tools).toBeInstanceOf(Array);
      expect(parsed.tools).toHaveLength(0);
    });
  });

  describe("excludes skills", () => {
    it("does NOT contain skills field (not implemented yet)", () => {
      const manifestWithSkills: PluginManifest = {
        ...fullManifest,
        skills: [
          {
            name: "test-skill",
            description: "A test skill",
            content: "Skill content here",
          },
        ],
      };
      const result = generateManifest(manifestWithSkills, new Map());
      const parsed = JSON.parse(result.content);
      expect(parsed).not.toHaveProperty("skills");
    });
  });

  describe("with minimal manifest", () => {
    it("works with just name and version", () => {
      const manifest: PluginManifest = {
        name: "minimal",
        version: "0.0.1",
        description: "Minimal plugin",
      };
      const result = generateManifest(manifest, new Map());
      expect(result.path).toBe("opencode.json");
      const parsed = JSON.parse(result.content);
      expect(parsed.name).toBe("minimal");
      expect(parsed.version).toBe("0.0.1");
      expect(parsed.description).toBe("Minimal plugin");
    });
  });

  describe("with full manifest", () => {
    it("produces correct structure matching example-logger output", () => {
      const result = generateManifest(fullManifest, multiHookCodeMap);
      const parsed = JSON.parse(result.content);

      // Verify structure matches example-logger output
      expect(parsed).toHaveProperty("name");
      expect(parsed).toHaveProperty("description");
      expect(parsed).toHaveProperty("version");
      expect(parsed).toHaveProperty("author");
      expect(parsed).toHaveProperty("license");
      expect(parsed).toHaveProperty("hooks");
      expect(parsed).toHaveProperty("tools");
      expect(parsed).toHaveProperty("discovery");
      expect(parsed.discovery).toHaveProperty("paths");

      // Verify hooks is object with true values
      for (const value of Object.values(parsed.hooks)) {
        expect(value).toBe(true);
      }
    });
  });
});

// ─── generateCommandFiles() Tests ────────────────────────────────────────────

describe("generateCommandFiles()", () => {
  it("returns empty array when manifest has no commands", () => {
    expect(generateCommandFiles(minimalManifest)).toEqual([]);
  });

  it("returns one file per command at command/<name>.md", () => {
    const manifest: PluginManifest = {
      name: "cmd-plugin",
      version: "1.0.0",
      description: "Plugin with commands",
      commands: [
        { name: "goal", description: "Set a goal", prompt: "Your goal: {{args}}" },
        { name: "goal-stop", description: "Stop the loop", prompt: "Stop now." },
      ],
    };
    const files = generateCommandFiles(manifest);
    expect(files).toHaveLength(2);
    expect(files[0].path).toBe("command/goal.md");
    expect(files[1].path).toBe("command/goal-stop.md");
  });

  it("replaces {{args}} with $ARGUMENTS in prompt", () => {
    const manifest: PluginManifest = {
      name: "cmd-plugin",
      version: "1.0.0",
      description: "",
      commands: [{ name: "test", prompt: "Do {{args}} now" }],
    };
    const [file] = generateCommandFiles(manifest);
    expect(file.content).toContain("$ARGUMENTS");
    expect(file.content).not.toContain("{{args}}");
  });

  it("includes description in YAML frontmatter", () => {
    const manifest: PluginManifest = {
      name: "cmd-plugin",
      version: "1.0.0",
      description: "",
      commands: [{ name: "go", description: "Run the thing", prompt: "Go!" }],
    };
    const [file] = generateCommandFiles(manifest);
    expect(file.content).toContain("description: Run the thing");
  });
});

// ─── generateAgentFiles() Tests ──────────────────────────────────────────────

describe("generateAgentFiles()", () => {
  it("returns empty array when manifest has no agents", () => {
    expect(generateAgentFiles(minimalManifest)).toEqual([]);
  });

  it("returns one file per agent at agent/<name>.md", () => {
    const manifest: PluginManifest = {
      name: "agent-plugin",
      version: "1.0.0",
      description: "",
      agents: [
        { name: "planner", description: "Plans tasks", prompt: "You plan things." },
        { name: "executor", description: "Executes tasks", prompt: "You execute." },
      ],
    };
    const files = generateAgentFiles(manifest);
    expect(files).toHaveLength(2);
    expect(files[0].path).toBe("agent/planner.md");
    expect(files[1].path).toBe("agent/executor.md");
  });

  it("includes description in YAML frontmatter", () => {
    const manifest: PluginManifest = {
      name: "agent-plugin",
      version: "1.0.0",
      description: "",
      agents: [{ name: "helper", description: "Helps you", prompt: "I help." }],
    };
    const [file] = generateAgentFiles(manifest);
    expect(file.content).toContain("description: Helps you");
  });

  it("includes tools in frontmatter when specified", () => {
    const manifest: PluginManifest = {
      name: "agent-plugin",
      version: "1.0.0",
      description: "",
      agents: [{ name: "coder", tools: ["bash", "read"], prompt: "I code." }],
    };
    const [file] = generateAgentFiles(manifest);
    expect(file.content).toContain("tools: [bash, read]");
  });
});

describe("adapterOverrides trust boundary", () => {
  it("sanitizes adapterOverrides.opencode relative path against pluginRoot", () => {
    const manifest: PluginManifest = {
      name: "override-test",
      version: "1.0.0",
      description: "Tests override sanitization",
      adapterOverrides: { opencode: "./custom-override.ts" },
    } as any;

    const result = generatePluginFile(manifest, new Map(), "/tmp/fake-plugin");

    expect(result.content).not.toContain("./custom-override.ts");
    expect(result.content).toContain("/tmp/fake-plugin/custom-override.ts");
  });

  it("blocks path traversal in adapterOverrides.opencode", () => {
    const manifest: PluginManifest = {
      name: "override-traversal-test",
      version: "1.0.0",
      description: "Tests override traversal blocking",
      adapterOverrides: { opencode: "../evil.ts" },
    } as any;

    const result = generatePluginFile(manifest, new Map(), "/tmp/fake-plugin");

    expect(result.content).not.toContain("../evil.ts");
    expect(result.content).not.toMatch(/['"]\.\.\/evil\.ts['"]/);
    expect(result.content).toContain("/tmp/fake-plugin/evil.ts");
  });

  it("emits a trust warning when an override is used", () => {
    const manifest: PluginManifest = {
      name: "override-warning-test",
      version: "1.0.0",
      description: "Tests override warning",
      adapterOverrides: { opencode: "./override.ts" },
    } as any;

    const result = generatePluginFile(manifest, new Map(), "/tmp/fake-plugin");

    expect(result.content).toContain("[agentplugins]");
    expect(result.content).toContain(
      "only install overrides from plugins you trust"
    );
  });
});

