/**
 * output-generators.test.ts — TDD RED phase tests
 *
 * These tests define the expected behavior of the output generator functions
 * for the OpenCode adapter: generatePluginFile() and generateManifest().
 */

import { describe, it, expect } from "vitest";
import type { PluginManifest, HookDefinition, FileOutput } from "@agentplugin/core";
import {
  generatePluginFile,
  generateManifest,
} from "../src/output-generators";

// ─── Test Fixtures ───────────────────────────────────────────────────────────

const minimalManifest: PluginManifest = {
  name: "test-plugin",
  version: "1.0.0",
  description: "A minimal test plugin",
};

const fullManifest: PluginManifest = {
  name: "my-opencode-plugin",
  version: "2.1.0",
  description: "A full-featured OpenCode plugin",
  author: "Test Author",
  license: "MIT",
  tools: [
    {
      name: "greet",
      description: "Greets the user",
      parameters: {
        type: "object",
        properties: {
          name: { type: "string", description: "Name to greet" },
        },
        required: ["name"],
      },
    },
  ],
  hooks: {
    sessionStart: {
      handler: {
        type: "inline",
        handler: async () => ({}),
      },
    },
    preToolUse: {
      handler: {
        type: "inline",
        handler: async () => ({}),
      },
    },
  },
};

const singleHookCodeMap = new Map<string, string>([
  ["tool.execute.before", `async ({ toolName, toolInput }) => {\n      // handler\n    }`],
]);

const multiHookCodeMap = new Map<string, string>([
  [
    "event",
    `async ({ event }) => {\n      if (event.type === "session.created") {\n        // sessionStart handler\n      }\n      if (event.type === "session.deleted") {\n        // sessionEnd handler\n      }\n    }`,
  ],
  ["tool.execute.before", `async ({ toolName, toolInput }) => {\n      // preToolUse handler\n    }`],
  ["tool.execute.after", `async ({ toolName, output }) => {\n      // postToolUse handler\n    }`],
]);

// ─── generatePluginFile() Tests ──────────────────────────────────────────────

describe("generatePluginFile()", () => {
  describe("file output structure", () => {
    it("returns FileOutput with path '{pluginName}.ts'", () => {
      const result = generatePluginFile(minimalManifest, singleHookCodeMap);
      expect(result.path).toBe("test-plugin.ts");
    });

    it("returns object with 'path' and 'content' properties", () => {
      const result = generatePluginFile(minimalManifest, singleHookCodeMap);
      expect(result).toHaveProperty("path");
      expect(result).toHaveProperty("content");
      expect(typeof result.path).toBe("string");
      expect(typeof result.content).toBe("string");
    });
  });

  describe("TypeScript content", () => {
    it("contains 'export default async function(ctx)' signature", () => {
      const result = generatePluginFile(minimalManifest, singleHookCodeMap);
      expect(result.content).toContain("export default async function(ctx)");
    });

    it("contains proper header comments", () => {
      const result = generatePluginFile(fullManifest, singleHookCodeMap);
      expect(result.content).toContain("// Auto-generated by AgentPlugin for OpenCode");
      expect(result.content).toContain(`// Plugin: ${fullManifest.name}`);
      expect(result.content).toContain(`// Description: ${fullManifest.description}`);
    });

    it("contains OpenCode plugin documentation comment block", () => {
      const result = generatePluginFile(fullManifest, singleHookCodeMap);
      expect(result.content).toContain("/**");
      expect(result.content).toContain(`${fullManifest.name} — OpenCode Plugin`);
      expect(result.content).toContain("This module was generated by @agentplugin/adapter-opencode");
      expect(result.content).toContain("*/");
    });

    it("returns object with hook keys from hookCodeMap", () => {
      const result = generatePluginFile(minimalManifest, singleHookCodeMap);
      expect(result.content).toContain('"tool.execute.before"');
    });

    it("contains handler invocation string from hookCodeMap", () => {
      const result = generatePluginFile(minimalManifest, singleHookCodeMap);
      expect(result.content).toContain("async ({ toolName, toolInput })");
    });
  });

  describe("with single hook", () => {
    it("generates valid TypeScript with one hook", () => {
      const result = generatePluginFile(minimalManifest, singleHookCodeMap);
      // Should have return statement with the hook
      expect(result.content).toContain("return {");
      expect(result.content).toContain("};");
    });
  });

  describe("with multiple hooks", () => {
    it("generates valid TypeScript with multiple hooks", () => {
      const result = generatePluginFile(fullManifest, multiHookCodeMap);
      expect(result.content).toContain("return {");
      expect(result.content).toContain("};");
      // All hooks from hookCodeMap should be present
      expect(result.content).toContain('"event"');
      expect(result.content).toContain('"tool.execute.before"');
      expect(result.content).toContain('"tool.execute.after"');
    });
  });

  describe("with minimal manifest", () => {
    it("works with just name and version", () => {
      const manifest: PluginManifest = {
        name: "minimal",
        version: "0.0.1",
        description: "",
      };
      const result = generatePluginFile(manifest, new Map());
      expect(result.path).toBe("minimal.ts");
      expect(result.content).toContain("export default async function(ctx)");
    });
  });
});

// ─── generateManifest() Tests ────────────────────────────────────────────────

describe("generateManifest()", () => {
  describe("file output structure", () => {
    it("returns FileOutput with path 'opencode.json'", () => {
      const result = generateManifest(minimalManifest, new Map());
      expect(result.path).toBe("opencode.json");
    });

    it("returns object with 'path' and 'content' properties", () => {
      const result = generateManifest(minimalManifest, new Map());
      expect(result).toHaveProperty("path");
      expect(result).toHaveProperty("content");
      expect(typeof result.path).toBe("string");
      expect(typeof result.content).toBe("string");
    });
  });

  describe("JSON structure", () => {
    it("contains valid JSON", () => {
      const result = generateManifest(minimalManifest, new Map());
      expect(() => JSON.parse(result.content)).not.toThrow();
    });

    it("contains name from manifest", () => {
      const result = generateManifest(fullManifest, new Map());
      const parsed = JSON.parse(result.content);
      expect(parsed.name).toBe(fullManifest.name);
    });

    it("contains version from manifest", () => {
      const result = generateManifest(fullManifest, new Map());
      const parsed = JSON.parse(result.content);
      expect(parsed.version).toBe(fullManifest.version);
    });

    it("contains description from manifest", () => {
      const result = generateManifest(fullManifest, new Map());
      const parsed = JSON.parse(result.content);
      expect(parsed.description).toBe(fullManifest.description);
    });

    it("contains author from manifest when present", () => {
      const result = generateManifest(fullManifest, new Map());
      const parsed = JSON.parse(result.content);
      expect(parsed.author).toBe(fullManifest.author);
    });

    it("contains license from manifest when present", () => {
      const result = generateManifest(fullManifest, new Map());
      const parsed = JSON.parse(result.content);
      expect(parsed.license).toBe(fullManifest.license);
    });

    it("defaults author to empty string when not provided", () => {
      const result = generateManifest(minimalManifest, new Map());
      const parsed = JSON.parse(result.content);
      expect(parsed.author).toBe("");
    });

    it("defaults license to 'MIT' when not provided", () => {
      const result = generateManifest(minimalManifest, new Map());
      const parsed = JSON.parse(result.content);
      expect(parsed.license).toBe("MIT");
    });
  });

  describe("hooks object", () => {
    it("contains hooks object mapping OpenCode hook names to true", () => {
      const result = generateManifest(fullManifest, multiHookCodeMap);
      const parsed = JSON.parse(result.content);
      expect(parsed.hooks).toBeDefined();
      expect(parsed.hooks).toBeInstanceOf(Object);
    });

    it("maps each hook key to true", () => {
      const result = generateManifest(fullManifest, multiHookCodeMap);
      const parsed = JSON.parse(result.content);
      expect(parsed.hooks["event"]).toBe(true);
      expect(parsed.hooks["tool.execute.before"]).toBe(true);
      expect(parsed.hooks["tool.execute.after"]).toBe(true);
    });

    it("contains only hooks that are in the hookCodeMap", () => {
      const result = generateManifest(fullManifest, singleHookCodeMap);
      const parsed = JSON.parse(result.content);
      const hookKeys = Object.keys(parsed.hooks);
      expect(hookKeys).toHaveLength(1);
      expect(hookKeys).toContain("tool.execute.before");
    });
  });

  describe("discovery paths", () => {
    it("contains discovery paths array", () => {
      const result = generateManifest(fullManifest, new Map());
      const parsed = JSON.parse(result.content);
      expect(parsed.discovery).toBeDefined();
      expect(parsed.discovery.paths).toBeInstanceOf(Array);
    });

    it("contains standard OpenCode plugin paths", () => {
      const result = generateManifest(fullManifest, new Map());
      const parsed = JSON.parse(result.content);
      expect(parsed.discovery.paths).toContain(".opencode/plugins/");
      expect(parsed.discovery.paths).toContain("~/.config/opencode/plugins/");
    });
  });

  describe("tools array", () => {
    it("contains tools array when manifest has tools", () => {
      const result = generateManifest(fullManifest, new Map());
      const parsed = JSON.parse(result.content);
      expect(parsed.tools).toBeInstanceOf(Array);
      expect(parsed.tools).toHaveLength(1);
    });

    it("contains tool with name, description, and parameters", () => {
      const result = generateManifest(fullManifest, new Map());
      const parsed = JSON.parse(result.content);
      expect(parsed.tools[0].name).toBe("greet");
      expect(parsed.tools[0].description).toBe("Greets the user");
      expect(parsed.tools[0].parameters).toBeDefined();
    });

    it("contains empty tools array when manifest has no tools", () => {
      const result = generateManifest(minimalManifest, new Map());
      const parsed = JSON.parse(result.content);
      expect(parsed.tools).toBeInstanceOf(Array);
      expect(parsed.tools).toHaveLength(0);
    });
  });

  describe("excludes skills", () => {
    it("does NOT contain skills field (not implemented yet)", () => {
      const manifestWithSkills: PluginManifest = {
        ...fullManifest,
        skills: [
          {
            name: "test-skill",
            description: "A test skill",
            content: "Skill content here",
          },
        ],
      };
      const result = generateManifest(manifestWithSkills, new Map());
      const parsed = JSON.parse(result.content);
      expect(parsed).not.toHaveProperty("skills");
    });
  });

  describe("with minimal manifest", () => {
    it("works with just name and version", () => {
      const manifest: PluginManifest = {
        name: "minimal",
        version: "0.0.1",
        description: "Minimal plugin",
      };
      const result = generateManifest(manifest, new Map());
      expect(result.path).toBe("opencode.json");
      const parsed = JSON.parse(result.content);
      expect(parsed.name).toBe("minimal");
      expect(parsed.version).toBe("0.0.1");
      expect(parsed.description).toBe("Minimal plugin");
    });
  });

  describe("with full manifest", () => {
    it("produces correct structure matching example-logger output", () => {
      const result = generateManifest(fullManifest, multiHookCodeMap);
      const parsed = JSON.parse(result.content);

      // Verify structure matches example-logger output
      expect(parsed).toHaveProperty("name");
      expect(parsed).toHaveProperty("description");
      expect(parsed).toHaveProperty("version");
      expect(parsed).toHaveProperty("author");
      expect(parsed).toHaveProperty("license");
      expect(parsed).toHaveProperty("hooks");
      expect(parsed).toHaveProperty("tools");
      expect(parsed).toHaveProperty("discovery");
      expect(parsed.discovery).toHaveProperty("paths");

      // Verify hooks is object with true values
      for (const value of Object.values(parsed.hooks)) {
        expect(value).toBe(true);
      }
    });
  });
});
